### ISSUE TITLE
code unavailable

### ISSUE THREAD

**Issue by LeSaUi** [yuwfan/HGN#1]
Hi, 

I'm sorry for not being good at english in advance.

I'm studying on NLP, GNN, etc..

I read your paper 'HGN' and I was about to run your code but I couldn't find any code about HGN.

So, would you plz let me know or provide your HGN code?

Thank you.

**Comment by yuwfan** [comment]
Hi,

Thanks for your interest in HGN. I am sorry for the late response since I was on a vacation in the previous couple of weeks. I will release the code next week. Please stay tuned.

Thanks!

**Comment by yuwfan** [comment]
Please see the released code.

**Comment by LeSaUi** [comment]
Thank you very much. I really appreciate it!
