### ISSUE TITLE
About Performance

### ISSUE THREAD

**Issue by chengzhipanpan** [yuwfan/HGN#2]
Hi,
 I wonder how much gain does the trick "using entity label prediction as normalization" gets in your experiments? 
There isn't a detailed ablation in your paper about this part.

**Comment by yuwfan** [comment]
Hi,

Sorry for the late response. The entity loss contributes very minor improvement (about 0.1 in Joint F1). Therefore, we don't include this ablation study in the latest version.

Thanks.

**Comment by chengzhipanpan** [comment]
Thank you very much.
