### ISSUE TITLE
Documentation for Multi-GPU training 

### ISSUE THREAD

**Issue by ByrdOfAFeather** [yuwfan/HGN#5]
Greetings! I'm working on a project that would be greatly benefited by having the ability to train this model in a variety of settings. I have a good deal of experience with the DFGN code this repository is based on, however, multi-gpu training seems to have been modified heavily. I was wondering if some guidance can be provided in this area. In particular **I am running out of GPU memory when moving the BERT encoder and graph model to a RTX 2080 (~11GB VRAM).**

I've tried settings local_rank = -1 which seems to be what is required for multi-gpu, as well I set data_parallel to true, and set n_gpu to 3. I've been unable to verify if this method works as it is unclear to me how to **specify which gpus the application should use** (the computer server I use has 4 and almost also has at least 1 in use. From what I can tell the code will try to grab devices 0, 1, 2 and I'm not seeing a way to change this). 

Another concern, from what I can tell in the code, the **models are only put on separate gpus after the initial loading**. In the original DFGN code, the models were loaded directly onto separate GPUs if multiple GPUs were specified. 

HGN:
```   
encoder.to(args.device)  # Note that args.device will be cuda in this case and not a specific gpu (I think)
model.to(args.device)
```

DFGN:

```       
encoder_gpus = [int(i) for i in args.encoder_gpu.split(',')]
model_gpu = 'cuda:{}'.format(args.model_gpu)

encoder = BertModel.from_pretrained(args.bert_model)
encoder.cuda(encoder_gpus[0])
encoder = torch.nn.DataParallel(encoder, device_ids=encoder_gpus)
encoder.eval()

# Set Model
model = GraphFusionNet(config=args)
model.cuda(model_gpu)
model.train()
`

**Comment by ByrdOfAFeather** [comment]
I got it working, so I will put the steps I used here if anyone else finds it helpful.
Firstly, I would like to note; I didn't use the docker environment. I know this is highly recommended on the page, but I do not have access to docker on the machine I am using to train.

###Disable Apex

I disabled apex for training. I was having a lot of issues getting this to work. For one, the DistributedDataParallel seems to be built for multiple machines rather than multiple GPUs. Though, it appears to be able to be used with multiple GPUs when using apex the torch.nn.DataParallel does not work; at least, I couldn't get it to work.
For how to do this in code, in train.py, comment out the following lines:

```
if args.fp16:
    with amp.scale_loss(loss_list[0], optimizer) as scaled_loss:
    scaled_loss.backward()
    torch.nn.utils.clip_grad_norm_(amp.master_params(optimizer), args.max_grad_norm) 
else:
```
and of course untab the lines under the else statement.
```
if args.fp16:
    try:
        from apex import amp
    except ImportError:
        raise ImportError("Please install apex from https://www.github.com/nvidia/apex to use fp16 training.")
    models, optimizer = amp.initialize([encoder, model], optimizer, opt_level=args.fp16_opt_level)
    assert len(models) == 2
    encoder, model = models

# Distributed training (should be after apex fp16 initialization)
if args.local_rank != -1:
    encoder = torch.nn.parallel.DistributedDataParallel(encoder, device_ids=[args.local_rank],
                                                        output_device=args.local_rank,
                                                        find_unused_parameters=True)

    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.local_rank],
                                                      output_device=args.local_rank,
                                                      find_unused_parameters=True)
```
Note that we can't just set args.fp16 to False, as this would still go to distributed training. So we need to ignore all apex related items completely. 

### Pick your GPUs

Change:
```
encoder.to(args.device)
model.to(args.device)
```

To:
```
encoder.to(0) # 0 being the numbered gpu. This can be whichever gpu you want to use ex. 0, 1, 2, etc
model.to(1) 
```

Since the encoder + data is huge, we want to put it on two GPUs:
Change:

```
optimizer = get_optimizer(encoder, model, args, learning_rate, remove_pooler=False)
#    if args.fp16:
#        try:
#            from apex import amp
#        except ImportError:
#            raise ImportError("Please install apex from https://www.github.com/nvidia/apex to use fp16 training.")
#        models, optimizer = amp.initialize([encoder, model], optimizer, opt_level=args.fp16_opt_level)
#        assert len(models) == 2
#        torch.distributed.init_process_group(backend="nccl")
#        encoder, model = models
#        encoder = torch.nn.parallel.DistributedDataParallel(encoder, device_ids=[0, 3])
```

To:
```
optimizer = get_optimizer(encoder, model, args, learning_rate, remove_pooler=False)
#    if args.fp16:
#        try:
#            from apex import amp
#        except ImportError:
#            raise ImportError("Please install apex from https://www.github.com/nvidia/apex to use fp16 training.")
#        models, optimizer = amp.initialize([encoder, model], optimizer, opt_level=args.fp16_opt_level)
#        assert len(models) == 2
#        torch.distributed.init_process_group(backend="nccl")
#        encoder, model = models
#        encoder = torch.nn.parallel.DistributedDataParallel(encoder, device_ids=[0, 3])

# Here we want 0 to be the device we defined earlier and 2 to be the second gpu we want to use the encoder with
encoder = torch.nn.DataParallel(encoder, device_ids=[0,2])   
```

### Ensure inputs get put on the right GPU
This next step seems like the "wrong way of doing it" to me, but it is in-line with how DFGN did it. Basically, after the encoder runs, we need to move the output to the model GPU. 

The inner-most for loop of train.py should look like the following:
```
for step, batch in enumerate(epoch_iterator):
    encoder.train()
    model.train()

    inputs = {'input_ids':      batch['context_idxs'],
              'attention_mask': batch['context_mask'],
              'token_type_ids': batch['segment_idxs'] if args.model_type in ['bert', 'xlnet'] else None}  # XLM don't use segment_ids
    batch_temp = {}
    batch_temp['context_encoding'] = encoder(**inputs)[0].detach().to("cuda:1")
    for key, value in batch.items():
            try:
                batch_temp[key] = value.detach().to("cuda:1")
            except Exception:
                try:
                    temp_list = []
                    for i in value:
                        temp_list.append(i.detach().to("cuda:1"))
                    batch_temp[key] = temp_list
                except Exception:
                    batch_temp[key] = value
        with open("log.txt", "w") as f:
            f.write(f"{batch_temp}")
        torch.cuda.set_device(1)
        start, end, q_type, paras, sents, ents, _, _ = model(batch_temp, return_yp=True)
```

This step also needs to be applied to csr_mhqa/utils.py in the eval_model function (the code is the same and will be omitted here)

After this step everything should work on a multi-gpu single system. Hopefully this is helpful.

**Comment by Tswings** [comment]
@ByrdOfAFeather 
I run the training code on my server based on your documentation. There is an out-of-memory exception occurs when I run the code (batch_temp['context_encoding'] = encoder(**inputs)[0].detach().to("cuda:1")).

"RuntimeError: CUDA out of memory. Tried to allocate 126.00 MiB (GPU 0; 10.92 GiB total capacity; 10.42 GiB already allocated; 79.50 MiB free; 12.05 MiB cached)"

[The server I use have 4 GPU, GTX 1080, ~11GB VRAM]

I try to set a smaller batch size (ex, 8). The question still can't be solved. Could you give me some suggestions to solve this question？

**Comment by ByrdOfAFeather** [comment]
@Tswings 

It's hard to say....

My particular use case only loaded in a partial amount of the original dataset, perhaps this is why I finally got around the OOM error. 

My best advice would be to double/triple check you are putting the graph model and encoder model on two different gpus and splitting the encoder between two gpus (at least - since you have 4 you could probably crank this up to 3 if you wanted to try that).

Aside from that, decreasing batch size is a good way to go, I believe there is also a batch size per gpu or something to that degree 

"args.batch_size = args.per_gpu_train_batch_size * max(1, args.n_gpu)" 

this will multiply your batch size, so also try reducing this setting. 

Hope this helps!

**Comment by Tswings** [comment]
> @Tswings
> 
> It's hard to say....
> 
> My particular use case only loaded in a partial amount of the original dataset, perhaps this is why I finally got around the OOM error.
> 
> My best advice would be to double/triple check you are putting the graph model and encoder model on two different gpus and splitting the encoder between two gpus (at least - since you have 4 you could probably crank this up to 3 if you wanted to try that).
> 
> Aside from that, decreasing batch size is a good way to go, I believe there is also a batch size per gpu or something to that degree
> 
> "args.batch_size = args.per_gpu_train_batch_size * max(1, args.n_gpu)"
> 
> this will multiply your batch size, so also try reducing this setting.
> 
> Hope this helps!

Many thanks, that's very helpful for me.
