### ISSUE TITLE
Docker image not up-to-date?

### ISSUE THREAD

**Issue by BryanSharp** [yuwfan/HGN#7]
Hey, I pulled the docker image and it seems the docker file tree does not match the get started doc, here is what I got from the DrQA folder:
![image](https://user-images.githubusercontent.com/8344245/113238782-04726b80-92dc-11eb-9c9d-3b91b7d665e4.png)

Could you provide some guidance on it? thx!

**Comment by yuwfan** [comment]
Hi @BryanSharp,

If you ran the command `docker run --gpus all -it -v /datadrive_c/yuwfan:/ssd -it studyfang/hgn:latest bash` from README, the working directory should be `/ssd` instead of `/workspace/DrQA.

Thanks.
