### ISSUE TITLE
Hyper-parameters for loss

### ISSUE THREAD

**Issue by xanhho** [yuwfan/HGN#8]
Hi,
Thank you for your paper and your code.

I see you use:
- ans_lambda = 1
- type_lambda = 1
- para_lambda = 1
- sent_lambda = 5
- ent_lambda = 1

Would you mind to share your motivations/reasons for why do you choose these numbers? Or you obtain it via experiments?

Thank you for your support.

**Comment by yuwfan** [comment]
Sorry for the late response. The motivation behind this is that these can be hyper-parameters to tune, but in our experiments we simply search sent_lambda {1, 3, 5} as supporting facts is the required task and this loss converge to small value quickly. For others, we just use 1 and haven't tuned on that.

**Comment by xanhho** [comment]
Oh, thank you for your response.
